//// -- LEVEL 1
//// -- Tables and References
  
// Creating tables
Table users {
  id bigint [pk]
  parent_id bigint [ref: > users.id, note: 'null if user is parent; otherwise, user is child account']
  name varchar [not null]
  email varchar [not null]
  email_verified boolean [note: 'only allow parent to login after email verified']
  phone_number varchar(20)
  phone_number_verified boolean
  updated_at timestamp
  deleted_at timestamp
}

Table user_details {
  id bigint [pk]
  user_id bigint [ref: - users.id]
  full_name varchar
  gender gender_type
  date_of_birth date
  avatar_url varchar
  address varchar
  city varchar
  state varchar
  country_code int(3)
  updated_at timestamp
  deleted_at timestamp
}

Table otps {
  id bigint [pk, increment]
  user_id bigint [ref: > users.id]
  otp varchar [note: 'this login opt is only valid in a period of time']
}

Table activities {
  id bigint [pk]
  content text
  content_url varchar [note: 'external url embbeded into the activity content']
  type activity_type
  status activity_status
  due_date date
  assigned_to bigint [ref: > users.id]
}

Table activity_media {
  id bigint [pk]
  medium_id bigint [ref: > media.id]
  activity_id bigint [ref: > activities.id]

  indexes {
    (medium_id, activity_id) [unique]
  }
}

Table media {
  id bigint [pk]
  title varchar
  description text
  url varchar [note: 'photos, audios, videos,... url']
}

Table activity_comments {
  id bigint [pk]
  activity_id bigint [ref: > activities.id]
  author bigint [ref: > users.id]
  content text
  content_url varchar
}

Table rewards {
  id bigint [pk]
  activity_id bigint [ref: > activities.id]
  user_id bigint [ref: > users.id]
  description text
  value int
  unit unit_type
  type reward_type
}

Table countries {
  code int(3) [pk]
  name varchar
  alpha2_code char(2)
  alpha3_code char(3)
}

Ref: user_details.country_code > countries.code

Enum gender_type {
  male
  female
  other [note: 'don\'t want to show gender']
}

Enum activity_type {
  disk_washing
  house_cleaning
  tree_watering
}

Enum activity_status {
  new
  assign
  inprogress
  postpone
  cancel
  complete
}

Enum unit_type {
  minute
  hour
  day
  money
  item
  others
}

Enum reward_type {
  money
  toy
  travel
  playing [note: 'playing @ VinKE, kizciti, tiNiWorld']
  watching [note: 'watching tv, youtube, movie,...']
  others
}
